services:
  weatherreportapi:
    image: murs000/weather_report_api:latest
    container_name: WeatherReport.API
    build:
      context: .
      dockerfile: WeatherReport.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5109
      - ConnectionStrings__DefaultConnection=Host=postgresdb;Port=5432;Database=WeatherDB;Username=myuser;Password=mypassword

      # API Keys and Email Settings
      - ExternalApi__ApiKey=88434e03b177155e26bf30fcadc1aced  # API key for external API
      - Jwt__AccessKey=ih5GO96Tw3WQJ4pl5jMmwKAwrXfBYRbcRUwp/kqCTJU=                # GPT access key
      - EmailSettings__FromEmail=m.mastali7@gmail.com          # From email
      - EmailSettings__SmtpUsername=m.mastali7@gmail.com       # SMTP username
      - EmailSettings__SmtpPassword=odjm vapt mgod dzgu        # SMTP password
    ports:
      - "5109:5109"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    container_name: WeatherReport.DB
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: WeatherDB
    ports:
      - "5433:5433"
    volumes:
      - ./containers/products-db:/var/lib/postgresql/data