# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  weatherreportapi:
    image: weatherreportapi
    build:
      context: .
      dockerfile: WeatherReport.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5109:5109
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
